services:
  - type: web
    name: smartstockai-backend
    runtime: python
    pythonVersion: "3.10.18"
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18
      - key: FLASK_ENV
        value: production 