services:
  - type: web
    name: smartstockai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    pythonVersion: 3.10.18
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production   